### ISSUE TITLE
Difference from binary liftOver

### ISSUE THREAD

**Issue by rkiminsilico** [jeremymcrae/liftover#1]
Hi, chr10:48414222 in hg19 (https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr10%3A48414207%2D48414236&hgsid=882144179_soT4oBAyiasogZtWmyBje5AwAUI5) is chr10:47325140 (https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr10%3A47325123%2D47325152&hgsid=882144179_soT4oBAyiasogZtWmyBje5AwAUI5), but liftover gives a different coordinate:
```
>>> import liftover
>>> lifter=liftover.ChainFile('hg19ToHg38.over.chain', 'hg19', 'hg38')
>>> lifter['chr10'][48414222]
[('chr10', 47325138, '-')]
```
Between hg19 and hg38, the gene's direction changed (from - to +), if this is relevant. Is any fix possible for this?

**Comment by jeremymcrae** [comment]
Thanks for the report! I think this is due to this package using 0-based coordinates, but the liftover binary using 1-based coordinates. Here's diagram that might help to clarify.

![bitmap](https://user-images.githubusercontent.com/1767732/90676147-65977400-e210-11ea-9b79-3d30ad5ee8c6.png)

I tried this coordinate on the liftover website, and it lifts to the same chr10:47325138 coord if entered as bed format:
`chr10 48414222 48414223` (start and end must differ for this)

but it gave the chr10:47325140 coordinate if entered as chrN:start-end format.

**Comment by rkiminsilico** [comment]
That makes sense. Thanks for the explanation!
