### ISSUE TITLE
bug found:The chromosome name was incorrect due to incorrect addition of the 'chr' prefix.

### ISSUE THREAD

**Issue by Dearwunan** [jeremymcrae/liftover#21]
example:
from liftover import ChainFile
>>> chainfile='hg19ToHg38.over.chain.gz'
>>> converter = ChainFile(chainfile, one_based=True)
>>> converter['NC_007605.1']
Traceback (most recent call last):
  File "src/liftover/chain_file.pyx", line 82, in liftover.chain_file.ChainFile.__getitem__
KeyError: 'NC_007605.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/liftover/chain_file.pyx", line 84, in liftover.chain_file.ChainFile.__getitem__
KeyError: 'chrNC_007605.1'

**Comment by jeremymcrae** [comment]
I think this is fine, 'NC_007605.1' doesn't exist in the converter. The reason it raises an error that names 'chrNC_007605.1' is that, for convenience, if the initial chromosome string doesn't occur in the converter, then it tries a 'chr' prefixed form. This is intended to be helpful because some human genome builds use a chr prefix while others don't.

You can view the chromosomes that can be lifted via `converter.keys()`, which for hg19ToHg38 shows the absence of 'NC_007605.1'.

**Comment by Dearwunan** [comment]
This exception should not be raised. It interrupts the running of program. I think, the liftover package should deal with the exception well,such as return None of [].

**Comment by jeremymcrae** [comment]
That's reasonable, thanks for the suggestion. I've updated the package to support this - version 1.3.0 returns [] for missing chromosomes e.g. `converter['NC_007605.1'][1000]`. Although, it's ~60% slower when the chromosome does not exist. And it still tries fixing the chr prefix first.
